version: 2

sources:
  - name: jaffle_shop
    database: raw
    tables:
      - name: customers
        description: source table of customers
      - name: orders
        description: source table of orders